name: Build

on:
  pull_request:

jobs:
  Release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
    env:
      ABI: ${{ matrix.abi }}
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install extra-cmake-modules gettext appstream

      - name: Build Release APK
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: assembleRelease
          gradle-version: wrapper
